baseURL: https://allenchan.me
languageCode: en-us
title: Allen Chan
theme: "PaperMod"

params:
  profileMode:
    enabled: true
    title: "DevOps x â˜• brewing x ðŸŽ¤ðŸŽ§ enthusiast" # optional default will be site title
    subtitle: "Sharing life hack tips and tricks here "
    imageUrl: "https://cal.com/api/avatar/4bcdd0cc-e764-4376-b2f4-c02af6c0c7f7.png"
    imageTitle: "headshot" 
    imageWidth: 180 
    imageHeight: 180 
    buttons:
      - name: Archive
        url: "/archives"
      - name: Have a â˜• chat with me 
        url: "https://cal.com/allen-q7kulv"
  socialIcons: # optional
    - name: "github"
      url: "https://github.com/Civon"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/chunyao-chan"
    - name: "email"
      url: "contact@allenchan.me"
    # - name: "pgp"
    #   url: ""
    # - name: "rss"
    #   url: "https://allenchan.me/index.xml"
    # - name: "twitter"
    #   url: "https://twitter.com/XXX"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
  ShowReadingTime: true
  author: "Allen Chan"
  contact: "contact@allenchan.me"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true
  ShowCodeCopyButtons: true
  editPost:
    URL: "https://github.com/Civon/blog-schrodinger/blob/main/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
  # enableEmoji: true

  #Google Analytics 4 optional
  env: #production
  # GoogleAnalytics: "G-00000XXXXX"
  sitemap:
    changefreq: daily
    filename: sitemap.xml
    priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: Glitches
      name: Glitch
      url: /categories/glitch/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20

permalinks:
  page:
    pages: /:slug
    # pages: /pages/:slug

    # notes: /note/:slug
    # tutorials: /training/:slug/
  # section:
  #   pages: /pages/
    # notes: /pages/
    # tutorials: /training/