baseURL: https://allenchan.me
languageCode: en-us
title: Allen Chan
theme: "PaperMod"

params:
  homeInfoParams:
    Title: Sup bruh ðŸ˜Ž
    Content: Sharing life hack tips and tricks here 

  socialIcons: # optional
    - name: "github"
      url: "https://github.com/Civon"
    # - name: "youtube"
    #   url: "https://www.youtube.com/channel/XXX"
    # - name: "twitter"
    #   url: "https://twitter.com/XXX"
    # - name: "kofi"
    #   url: "https://buymeacoffee.com/XXX"
    - name: "rss"
      url: "https://allenchan.me/index.xml"
  ShowReadingTime: true
  author: "Allen Chan"
  contact: "contact@allenchan.me"
  feedlinks: true
  copyright: "<!--Creative Commons License-->This site is licensed under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/).<!--/Creative Commons License-->"
  mobileMenu: true
  # enableEmoji: true

  #Google Analytics 4 optional
  env: #production
  # GoogleAnalytics: "G-00000XXXXX"
  sitemap:
    changefreq: daily
    filename: sitemap.xml
    priority: 0.5

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  section:
    - HTML
    - RSS
    - JSON

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20

permalinks:
  page:
    pages: /:slug
    # pages: /pages/:slug

    # notes: /note/:slug
    # tutorials: /training/:slug/
  # section:
  #   pages: /pages/
    # notes: /pages/
    # tutorials: /training/